set $cors_origin "";
set $cors_cred "";
set $cors_header "";
set $cors_method "";
set $cors_content_type "";
set $cors_content_length "";

# if ($http_origin ~ '^https?://(localhost:15000|bizarre\.local)$') {
#       set $cors_origin $http_origin;
#       set $cors_cred true;
#       set $cors_header $http_access_control_request_headers;
#       set $cors_method $http_access_control_request_method;
# }

# allow all
set $cors_origin $http_origin;
set $cors_cred true;
set $cors_header $http_access_control_request_headers;
set $cors_method $http_access_control_request_method;

if ($request_method = OPTIONS) {
        set $cors_content_type 'text/plain';
        set $cors_content_length '0';
}

add_header Access-Control-Allow-Origin $cors_origin;
add_header Access-Control-Allow-Credentials $cors_cred;
add_header Access-Control-Allow-Headers $cors_header;
add_header Access-Control-Allow-Methods $cors_method;
add_header Content-Type $cors_content_type;
add_header Content-Length $cors_content_length;

if ($request_method = 'OPTIONS') {
        # Tell client that this pre-flight info is valid for 20 days
        return 204;
}