proxy_pass https://{{CLOUD_SERVER_NAME}};  # No trailing "/" means path is included

proxy_set_header Host {{CLOUD_SERVER_NAME}};
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_ssl_server_name on;
proxy_ssl_name {{CLOUD_SERVER_NAME}};